from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Dict, List


@dataclass
class PluginResult:
    """Represents a finding generated by a service plugin."""

    severity: str
    title: str
    description: str
    remediation: str
    evidence: str


class ServicePlugin:
    """Base class for scanner plugins."""

    name: str = ""
    metadata: Dict[str, str] | None = None

    def matches(self, device: Dict) -> bool:
        raise NotImplementedError

    def evaluate(self, device: Dict) -> List[PluginResult]:
        raise NotImplementedError
